import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const gillSans = localFont({
  src: "../app/fonts/GillSans.otf",
  variable: "--font-gill-sans",
});

const opus = localFont({
  src: "../app/fonts/Opus.ttf",
  variable: "--font-opus",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`text-[#382F26] ${opus.variable}  ${gillSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
